### ISSUE TITLE
Support disabling parallel?

### ISSUE THREAD

**Issue by awlayton** [danielstjules/mocha.parallel#10]
It would be very useful to have a way to essentially disable this module, turning all the `parallel`s into regular `describe`s, via an environment variable.

I want this for the case when a test starts failing, I would like to be able to make it not parallel so the debug output from the tests is more intelligible. Is there any chance of adding such functionality?

**Comment by danielstjules** [comment]
Sure! I might be able to add it this weekend, otherwise a PR would be great
