### ISSUE TITLE
mocha -g hides tests, but still runs them

### ISSUE THREAD

**Issue by pornel** [danielstjules/mocha.parallel#14]
```js
const parallel = require('mocha.parallel');

parallel('test', function() {
    it('excluded', function() {
        console.error("Should not run");
    });

    it('included', function() {
    });
});
```

```sh
mocha -g included
```

With regular `describe` it runs only one test. With `parallel` it prints "Should not run".

This is unfortunate, because mocha's grep function is very useful at checking whether tests also fail when run in isolation, and to limit amount of noise logged during tests. Both cases are especially important when tests are run in parallel.

**Comment by danielstjules** [comment]
Sorry for the very late reply!

Unfortunately, there doesn't seem to be an easy way to get a reference to an instance of the mocha runner during execution, which holds all grep/filtering logic. And alternatives such as reading options and reimplementing seems too fragile. Open to other suggestions though!
