### ISSUE TITLE
Context of `parallel`?

### ISSUE THREAD

**Issue by amilajack** [danielstjules/mocha.parallel#16]
`parallel` seems to have an unusual context. For example:

```js
// test.js

parallel('Some test', function () {
  this.slow(2000)
})
```

would return:

```
Cannot read property 'slow' of undefined
```

It seems as if the context of parallel is not the function.

**Comment by danielstjules** [comment]
Somewhat related to https://github.com/danielstjules/mocha.parallel/issues/5#issuecomment-152943025 This may not be a problem in the latest mocha, so I'll need to test if a solution is available to this issue :)

**Comment by amilajack** [comment]
Maybe test cases should be added to check for this.

**Comment by danielstjules** [comment]
Fixed by https://github.com/danielstjules/mocha.parallel/pull/17 :)

**Comment by danielstjules** [comment]
Fixed and published in 0.13!

**Comment by amilajack** [comment]
Great! I'll try testing this out.

**Comment by thgreasi** [comment]
Should we open a new issue for properly supporting all the context assigned props, or should we re-open this one (since the issue title is covering a wider range of things to support)?
Eg:
```js
describe('a', function() {

  before(function() {
    this.x = 1;
  });

  parallel('b', function() {

    before(function() {
      this.x = 2;
    });

    it('c', function() {
      console.log(this.x); // undefined
    });
  });
});
```
