### ISSUE TITLE
Nightmare example?

### ISSUE THREAD

**Issue by gavinengel** [danielstjules/mocha.parallel#2]
@danielstjules Sorry to bother you, but would you have time to include a nightmare.js & mocha example in your readme?  I like chai as well, if you could be bothered to include that as well/additionally.  Or perhaps a directory of examples?  I'd *really* love to reduce the time of nightmare.js/mocha tests.

**Comment by danielstjules** [comment]
Should be able to write something up later today. In the meantime, take a look at nightmare's test suite :) https://github.com/danielstjules/nightmare/blob/29bbc19d44cf4031fd4c954bad4b5f2915e5b2af/test/index.js

**Comment by gavinengel** [comment]
hmm, that link seems to be broken Daniel, would you recheck that please?

**Comment by danielstjules** [comment]
Fixed :) Forgot I deleted my fork

**Comment by gavinengel** [comment]
Perfecto, gracias Señor!
