### ISSUE TITLE
Multiple describe issue

### ISSUE THREAD

**Issue by GranitB** [danielstjules/mocha.parallel#21]
When ever I use 2 describe that has many its it doesn't work 

```
parallel('delays', function () {
  describe('Test Mocha', function () {
    it('test',function(done){
    });
    it('test',function(done){
    })
 });
 describe('Test Mocha', function () {
    it('test',function(done){
    });
    it('test',function(done){
    })
 });
});

```

the its are running in unordered  form and the test fails

**Comment by danielstjules** [comment]
Yea, sorry. That behavior isn't supported. Instead I'd suggest making the parent a describe, and each nested suite a parallel. From the readme:

> Supports hooks, pending or skipped specs/suites via parallel.skip() and it.skip(), but not nested suites.

**Comment by GranitB** [comment]
My issue is that I need to run multiple describe in parallel mode not the it s

**Comment by danielstjules** [comment]
Unfortunately, it's just not supported at the moment, and I haven't had much time to work on this project.
