### ISSUE TITLE
Supporting Mochas "this.retries(N);"

### ISSUE THREAD

**Issue by ZacasaurousRex** [danielstjules/mocha.parallel#23]
Mocha supports retrying an individual test, and all tests. [retry-tests](https://mochajs.org/#retry-tests)

```javascript
describe('retries', function() {
  // Retry all tests in this suite up to 4 times
  this.retries(4);

  beforeEach(function () {
    browser.get('http://www.yahoo.com');
  });

  it('should succeed on the 3rd try', function () {
    // Specify this test to only retry up to 2 times
    this.retries(2);
    expect($('.foo').isDisplayed()).to.eventually.be.true;
  });
});
```
Having this in Parallel environments at the individual test level would be and incredibly helpful feature.

**Comment by danielstjules** [comment]
Agreed that it would be helpful! Unfortunately, I don't have the time to contribute this functionality, though would gladly review any PR!

**Comment by rkpareek** [comment]
Are you going to fix this?. I am facing this issue since a long time.
