### ISSUE TITLE
Support descriptions for hooks like mocha

### ISSUE THREAD

**Issue by SanderRonde** [danielstjules/mocha.parallel#24]
Mocha supports the ability to describe hooks as well. 
This is not very well documented on their main documentation page but it is possible, as can be seen here https://github.com/mochajs/mocha/blob/2bb2b9fa35818db7a02e5068364b0c417436b1af/lib/suite.js#L200.
Doing this in mocha.parallel will throw an error because at this line: https://github.com/danielstjules/mocha.parallel/blob/master/lib/parallel.js#L243 the hooks will only take one argument, namely the function. It will then attempt to execute the description string which throws an error.

**Comment by danielstjules** [comment]
Thanks for the issue! Workaround here to prevent the code from throwing an exception: https://github.com/danielstjules/mocha.parallel/commit/068eaaee5115b19a90e0e8dda9e8cb4af0ea37c1 If interested, would welcome PRs to fully support named hooks, though I don't see a ton of benefit.
