### ISSUE TITLE
Limit Concurrent Tests

### ISSUE THREAD

**Issue by ZacasaurousRex** [danielstjules/mocha.parallel#26]
An option such as `parallel.concurrency(4)` to limit four tests running at the same time would be helpful. I've implemented this change and can submit a pull request if that'd be easier, but I'm using an npm library called [semaphore](https://github.com/abrkn/semaphore.js) as a module dependency that would be added to the package.json to limit the tests.

**Comment by danielstjules** [comment]
I think I'd be open to it :) Could I see the changes you made? Would be curious how you've implemented it so far

**Comment by ZacasaurousRex** [comment]
Yeah fill free to look at the changes. I made the pull request so you can review them. Let me know if there are any coding standards you follow, or implementation changes.

**Comment by danielstjules** [comment]
Thanks again!
