### ISSUE TITLE
process.listeners is not a function

### ISSUE THREAD

**Issue by cj** [danielstjules/mocha.parallel#28]
I'm using node `6.9.1` and mocha `3.20`.

```javascript
import parallel from 'mocha.parallel'

const sleep = ms => {
  return new Promise(resolve => setTimeout(resolve, ms))
}

describe('loginPage', () => {
  it('should do something', async done => {
    sleep(2000)
    expect(true).to.equal(true)
    console.log('cow')
    done()
  })

  it('should submit the form', async done => {
    console.log('moo')
    done()
  })
})
```

**Comment by danielstjules** [comment]
Are you still experiencing this issue with the latest version of node? Are you using babel? Is something overwriting the `process.listeners` global? I haven't been able to replicate so far.

**Comment by danielstjules** [comment]
Ah, I think you're trying to run these in the context of a browser (with browserify or other)? That would explain why `process.listeners` is undefined. Sorry, but mocha.parallel only works with mochajs in node, not in the browser. But if I guessed wrong, feel free to reopen!
