### ISSUE TITLE
Using parallel braking execution time counter

### ISSUE THREAD

**Issue by Kostanos** [danielstjules/mocha.parallel#30]
When I run in parallel my tests, the execution time is not reported correctly:

    ✓ class import and initialization (201ms)
    ✓ normalize (199ms)
    ✓ set (198ms)
    ✓ move (196ms)
    ✓ remove (195ms)
    ✓ performance (195ms)
    6 passing (215ms)

When it should be like this:

    ✓ class import and initialization (2ms)
    ✓ normalize
    ✓ set (1ms)
    ✓ move (1ms)
    ✓ remove
    ✓ performance (177ms)
    6 passing (189ms)

**Comment by danielstjules** [comment]
Can you post some example code demonstrating that behavior?

``` javascript
var parallel = require('mocha.parallel');

parallel('example', function() {
  it('a', function(done) {
    setTimeout(done, 1);
  });

  it('b', function(done) {
    setTimeout(done, 50);
  });

  it('c', function(done) {
    setTimeout(done, 100);
  });

  it('d', function(done) {
    setTimeout(done, 120);
  });
});
```

```
$ mocha test.js


  example
    ✓ a
    ✓ b (56ms)
    ✓ c (101ms)
    ✓ d (125ms)


  4 passing (143ms)
```

**Comment by Kostanos** [comment]
I think the issue here is because the code running actually not in parallel (you mentioned it already in description) and nothing we can do about it. Or maybe you know how can improve this?

    "use strict"

    var parallel = require('mocha.parallel');

    parallel('example', function() {
      it('a', function(done) {
        let a = 0;
        for(let i=0;i<=100;i++){
          a *= i;
        }
        done();
      });

      it('b', function(done) {
        let a = 0;
        for(let i=0;i<=10000;i++){
          a *= i;
        }
        done();
      });

      it('c', function(done) {
        let a = 0;
        for(let i=0;i<=100000;i++){
          a *= i;
        }
        done();
      });

      it('d', function(done) {
        let a = 0;
        for(let i=0;i<=10000000;i++){
          a *= i;
        }
        done();
      });
    });

Result:

    $ mocha -R spec --slow 0 test.js 
      example
        ✓ a (121ms)
        ✓ b (120ms)
        ✓ c (120ms)
        ✓ d (118ms)
      4 passing (141ms

**Comment by danielstjules** [comment]
mocha.parallel is only meant for asynchronous tests, so there's no benefit for synchronous blocking logic as in the above example. However, I can probably fix the logic to correctly report those numbers for sync tests.

**Comment by Kostanos** [comment]
sure, fixing numbers would help. thank you
