### ISSUE TITLE
Mochawesome addContext

### ISSUE THREAD

**Issue by shyam81992** [danielstjules/mocha.parallel#32]
I need native test object inside test (it) 

const addContext = require('mochawesome/addContext');
 
describe('test suite', function () {
  it('should add context', function () {
    // context can be a simple string 
    addContext(this, 'simple string');
});
});

**Comment by danielstjules** [comment]
Sorry, I think that'll be tough to achieve. Would welcome a PR, but it'd be easier to just just drop mocha.parallel.
