### ISSUE TITLE
"it.skip" is not working in parallel.

### ISSUE THREAD

**Issue by Kuldeep-Chhipa** [danielstjules/mocha.parallel#34]
I am using that code for parallel

parallel("A. Delete the particular app of customer testcases..", function () {
    this.timeout(99000);
it.skip("\n1. It should show error message when delete the app of other partner's customer", function (done) {
        server
            .delete(commonUtility.appByPartner2().endPoint)
            .set('Content-Type', 'application/json')
            .expect('Content-Type', /json/)
            .end(function (err, res) {
                if (!err) {
                    chai.expect(res.body).to.have.property('status', false);
                    done();
                }
                else
                    throw res.error;
            });
    });
});

It.skip was skipping the case in the console but in the back, the case was running and performs the changes.
When I check it manually then I got the status=false but it should be true.(because of skip)

Please look into this. or else I was doing wrong.

**Comment by rkpareek** [comment]
I am also facing this issue,

**Comment by ankiitsinghh** [comment]
I am also facing the same issue.

**Comment by PawanDixit23** [comment]
When I run this script,It shows the cases is skip but at the back end the cases are not skip at the skip function is also running,So now I am not able to skip the function using mocha.

**Comment by danielstjules** [comment]
Not sure if this was a regression, but fixed in 0.15.3! https://github.com/danielstjules/mocha.parallel/commit/8ce11237950e0ca9a231653449096e0599c9daa9
