### ISSUE TITLE
Skip tests that don't declare a function

### ISSUE THREAD

**Issue by ze6ke** [danielstjules/mocha.parallel#39]
This is certainly a feature request and not a bug.  But, it'd be a nice feature.  Also, thanks for this library, it's nice to work with.

Mocha allows you to declare a test without passing a function and it will automatically skip the test.  The following code is valid and both tests will be skipped

```
describe('some tests', function () {
  it('not implemented yet')
  it.skip('also not implemented', function () {})
})
```
mocha.parallel doesn't accept the same setup, so this gives an error on the first test.
```
parallel('some tests', function () {
  it('not implemented yet')
  it.skip('also not implemented', function () {})
})
```

It's easy enough to work around by calling it.skip, but it makes migration to mocha.parallel a little more difficult.

**Comment by tosbaha** [comment]
You can use `xit` instead of `it` to skip tests. It is supported by this library.

**Comment by ze6ke** [comment]
Ahh.  That means that there are two valid workarounds for this.  Thanks Tosbaha.

**Comment by danielstjules** [comment]
Fixed in https://github.com/danielstjules/mocha.parallel/issues/39 !

**Comment by ze6ke** [comment]
Sweet!

Thank you.

z
