### ISSUE TITLE
How to get title of parallel and it present under parallel

### ISSUE THREAD

**Issue by darklord549** [danielstjules/mocha.parallel#43]
Consider following code, i need suite1 and test1 and test2 in variables. Could you please help me in this?

parallel('suite1', function() {
  it('test1', function(done) {
    setTimeout(done, 500);
  });

  it('test2', function(done) {
    setTimeout(done, 500);
  });
});

**Comment by danielstjules** [comment]
Could you define them in variables ahead of time?

```javascript
var suite = "my cool suite";
parallel(suite, function() {
  // ...
});
```
