### ISSUE TITLE
Cannot find module 'domain' when used with mocha-casperjs

### ISSUE THREAD

**Issue by mjyoung** [danielstjules/mocha.parallel#6]
On Node v5.x / npm v3.x, 

The code:
var parallel = require('mocha.parallel');

produces the error: 
```
Error: Cannot find module 'domain'
  /node_modules/mocha.parallel/index.js:2
```

If I manually npm install domain --save, and

```
ReferenceError: Can't find variable: System
  /node_modules/domain/dist/lib/Domain.js:1
```

Any idea how to resolve?

**Comment by danielstjules** [comment]
Hm, it's not an issue with the node or npm versions, since the domain api is still available:
```
$ node --version
v5.0.0
dstjules:~/git/mocha.parallel (master=)
$ npm --version
3.3.6
dstjules:~/git/mocha.parallel (master=)
$ npm test

> mocha.parallel@0.10.0 test /Users/dstjules/git/mocha.parallel
> mocha test.js



  parallel
    ✓ runs specs in parallel (900ms)
    ✓ isolates parallel suite execution (1349ms)
...
```

**Comment by danielstjules** [comment]
If you just do:
``` javascript
var domain = require('domain');
```
Does it still error? If the code is being executed within casperjs/phantomjs (rather than node creating instances of casperjs/phantomjs), that might explain it.

**Comment by mjyoung** [comment]
Yes, if I do var domain = require('domain'), it still errors out in Domain.js saying `Undefined variable: System`. I think it may be because I'm running my tests using `mocha-casperjs test.js`, so this may not specifically be related to mocha.parallel

**Comment by danielstjules** [comment]
Yeah, sorry :( It's an issue with casperjs.

```
$ cat test.js
var domain = require('domain');

dstjules:~/Desktop
$ casperjs test.js
CasperError: Can't find module domain

  /usr/local/lib/node_modules/casperjs/bin/bootstrap.js:262 in patchedRequire
  test.js:1
```

So mocha.parallel won't work with it, as domains are required. Without domains, debugging's very difficult as it's hard to point an error as belonging to a specific test.
