### ISSUE TITLE
new requirement - support this.timeout()

### ISSUE THREAD

**Issue by mkatsoho** [danielstjules/mocha.parallel#7]
I find out mocha.parallel does not support timeout() function, which mocha supports. 

# js codes:

parallel( "volumn test to read/write user profile", function(){
    this.timeout(12000);        // case timeout 
    it('spec', function(done){
        done();
    });
})

# error info:

$ mocha test/userProfile2.js 
/home/mk/dev/volumn-test/test/userProfile2.js:261
    this.timeout(12000);        // case timeout 
         ^
TypeError: undefined is not a function

# versions used: 

$ npm ls mocha mocha.parallel
/home/mk
├── mocha@2.2.5 
└── mocha.parallel@0.11.2

**Comment by danielstjules** [comment]
Sorry, it's out of scope for this little hack. See https://github.com/danielstjules/mocha.parallel/issues/5#issuecomment-152943025

**Comment by mkatsoho** [comment]
Thanks for your updates.

**Comment by danielstjules** [comment]
It's not available in the latest release! :)
