### ISSUE TITLE
Support "this.timeout()" for hooks and test-level

### ISSUE THREAD

**Issue by andrewwakeling** [danielstjules/mocha.parallel#8]
Mocha supports the following.

Setting the timeout at the test level:

```javascript
function it(done) {
  this.timeout(0);
}
```

Settings the timeout for before/after/beforeEach/afterEach hooks:

```javascript
function before(done) {
  this.timeout(0);
}
```

It would be great if these features were supported as it allows for better granularity around timeouts and allows tests to fail faster.

**Comment by danielstjules** [comment]
Sorry, it's not currently possible: https://github.com/danielstjules/mocha.parallel/issues/5#issuecomment-152943025

Related: https://github.com/danielstjules/mocha.parallel/issues/7

**Comment by andrewwakeling** [comment]
Thanks for the incredibly prompt reply @danielstjules.

**Comment by danielstjules** [comment]
This should be supported in the latest release :)
